language: node_js
node_js:
- 10
- node
install:
- travis_retry npm ci
script:
- npm run lint
- npm run build
- npm run build-app
deploy:
- provider: npm
  email: stefandesu@exo.pm
  api_key:
    secure: gbbiOerXvGimKrcxkjALwpT2lkCbL1HwEpmN6GtIVXcXuQOkuYSXtppwhgbDp6blB86zTM9P1MtWScG16mCy9YbrlutLC2/ket4oyGLNt102pKt7r1jNcZEhIqVkBwM72qeDE5e9Ds2sWiiVgGkVJOKAKZbo49p2IrrtZoTGBRzBnZ253Gu+x+XRKfGraIpkbCoNu0KmfzawXIrVUwxFEwFCEthUidgaRP1YQorlNJoaS4n8/A5l0M5lV6Eag9HK7RHqU38ZcFXfI0UtLn2Glyg5ZH4ek9pzVO4x4E2TGqrN5c8b9UimSV4E80c74yA5pL6lBxWhJuNe7jU85maiimQo9CkGmC6CXJhqFbp7BmFquBJ7OsyW3wo7DTfbVlKEGJsSrG9oJHPo0YW5/uIQOvfZWlPO3IooFkoEKa6RRRQL4mLwcAKKdRTURbRz9N9TaeY4sZXWN6VGY6CpfbOEsZHbwQ7sFedrp5jcMk89VJVkapiN6mJwC4CEP4wgROGX6/Wq9a7J2tnbhstlKasvZoJDl0FpHpA9EXQFKTHk2znGMAJuXbv+S6whykoH1SsUqaRkaKBcvbeznnK4/mdE9/esQ6RN637mfwhp08LpT3oL2Z6z3lO5tR0wUNa3SPn52KNQtfT3UGbQdh7rYxRIPijbhK1UYaRYo3ZXZOEHk/I=
  on:
    tags: true
    repo: stefandesu/vue-flexible-table
    node_js: node
- provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
