language: node_js
node_js:
  - "11"
install:
  - travis_retry npm ci
script:
  - npm run lint
  - npm run build
  - npm run build-app
deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
